# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Sync

# Model Form Field configuration
form: $/awebsome/serverpilot/models/sync/fields.yaml

# Model Class name
modelClass: Awebsome\Serverpilot\Models\Sync

# Default redirect location
defaultRedirect: awebsome/serverpilot/syncs
