databases:
    label: Databases
    view:
        list: $/awebsome/serverpilot/models/database/columns.yaml
        toolbarButtons: create|delete
        clickable: 'false'
    manage:
        form: $/awebsome/serverpilot/models/database/on-app-fields.yaml
        list: $/awebsome/serverpilot/models/database/columns.yaml
        clickable: 'false'
